### ISSUE TITLE
与spring-boot 整合 org.reflections.ReflectionsException: could not get type for name 

### ISSUE THREAD

**Issue by zjnxyz** [xtuhcy/gecco-spring#1]
> org.reflections.ReflectionsException: could not get type for name 
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390) ~[reflections-0.9.11.jar:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381) [reflections-0.9.11.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:126) [reflections-0.9.11.jar:na]
	at com.geccocrawler.gecco.spider.SpiderBeanFactory.<init>(SpiderBeanFactory.java:72) [gecco-1.2.8.jar:1.2.8]
	at com.geccocrawler.gecco.GeccoEngine.run(GeccoEngine.java:225) [gecco-1.2.8.jar:1.2.8]
Caused by: java.lang.ClassNotFoundException: 
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_101]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388) ~[reflections-0.9.11.jar:na]
	... 4 common frames omitted

我debug进去后发现 store 中的nmap 有key 会出现空字符

**Comment by zjnxyz** [comment]
我debug进去后发现 store 中的nmap 有key 会出现空字符
